# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klxBjI0HDJ70AtmBM1Jg3JoiC478NDJE
"""

!pip install twilio

!pip install playsound==1.2.2

import cv2
import numpy as np
from tensorflow.keras.utils import load_img,img_to_array
from tensorflow.keras.models import load_model
from twilio.rest import Client
import getpass
from playsound import playsound
msg_sent = False
model = load_model('/content/drive/MyDrive/archive.zip (Unzipped Files)/forest1.h5')
video = cv2.VideoCapture("/content/drive/MyDrive/demo_video 1.mp4")
def send_message():
    global phno
    account_sid = os.environ['TWILIO_ACCOUNT_SID']
    auth_token = os.environ['TWILIO_AUTH_TOKEN']
    client = Client(account_sid,auth_token)
    msg = client.messages.create(
        body="Fire Detected! Get to safety immediately!!!!",
        from_=os.environ['TWILIIO_PHONE_NUMBER'],
        to=phno
    )
    print(msg.sid)
    print("Fire Detected")
    print("SMS Sent")
phno = getpass.getpass(prompt="Enter your phone number with the country code:")

"""**Alerting code**"""

v = 0
while True:
    success,frame = video.read()
    cv2.imwrite('output.jpg',frame)
    img = load_img(s,target_size=(128,128))
    x = img_to_array(img)
    x = np.expand_dims(x,axis=0)
    predict = model.predict(x)
    y = int(predict[0][0])
    if y==1:
        if not msg_sent:
            send_message()
            msg_sent = True
            playsound('alert.mp3')
    else:
        print("No Forest Fire Detected")
    cv2.imshow("Image",img)
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
video.release()
cv2.destroyAllWindows()